header:
  license:
    spdx-id: LGPL-3.0-or-later
    copyright-owner: BYU Configurable Computing Laboratory
    content: 'SPDX-License-Identifier: LGPL-3.0-or-later'

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '.github'
    - '**/*.txt'
    - '**/*.json'

  comment: on-failure