name: Add Release Tag to Release Commit
on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  build:
    name: Add release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5

      - name: Get release version
        id: get_release_version
        run: |
          pip install toml
          echo "release_version=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")" >> $GITHUB_OUTPUT

      - name: Commit release version tag
        env:
          RELEASE_VERSION: 'v${{ steps.get_release_version.outputs.release_version }}'
        run: |
          git tag ${{ env.RELEASE_VERSION }}
          git push origin ${{ env.RELEASE_VERSION }}
          echo 'Applied tag "${{ env.RELEASE_VERSION }}" to release commit.'