name: Documentation

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache documentation dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            poetry.lock
          key: ${{ runner.os }}-poetry-docs-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-docs-

      - name: Install documentation dependencies
        run: |
          pip install poetry
          poetry lock
          poetry install --only docs

      - name: Sphinx build
        run: |
          cd sphinx-docs
          SPHINXOPTS="-W" poetry run make html # The -W flag throws all warnings as errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: sphinx-docs/_build/html/
          force_orphan: true
          allow_empty_commit: ${{ github.event_name == 'workflow_dispatch' }} # Force-commit if run using workflow dispatch
