name: Require PR into main from pre_release

on:
  pull_request:
    branches:
      - actiongate-main

jobs:
  require-pre-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        run: |
            branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            echo "branch=$branch" >> $GITHUB_OUTPUT
            echo Attempting to pull from $branch branch...
        id: extract_branch
      - name: Confirm that PR is from pre_release branch
        run: |
            if [ ${{ steps.extract_branch.outputs.branch }}=='actiongate-pre' ]; then
                echo "PR is from the correct branch; pass."
            else
                echo "::error ::This PR must come from the 'pre_release' branch in order to merge into main."
                exit 1
            fi
