# 'Extract Branch Name' step based on aborilov's Stack Overflow answer here: https://stackoverflow.com/a/58035262/14797164

name: Require PR into main from pre_release

on:
  pull_request:
    branches:
      - main

jobs:
  require_pre_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        run: |
            branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            echo "branch=$branch" >> $GITHUB_OUTPUT
            echo PR started from \'$branch\' branch.
        id: extract_branch
      - name: Confirm that PR is from pre_release branch
        run: |
            if [ "${{ steps.extract_branch.outputs.branch }}" == "pre_release" ]; then
                echo "PR is from the correct branch; pass."
            else
                echo "::error ::This PR must come from the 'pre_release' branch in order to merge into main."
                exit 1
            fi
