name: “Require pre_release label on PRs into main”

on:
  pull_request:
    branches:
      - actiongate-main

jobs:
  require-label:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        run: |
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
            echo "Attempting to pull from ${{ branch }} branch..."
        id: extract_branch
      - name: Only accept PRs from pre_release
        if: ${{ !steps.extract_branch.outputs.branch=='actiongate-pre' }}
        run: |
            echo "::error ::This PR must come from the 'pre_release' branch in order to merge into main."
            exit 1
