name: Test Prepare Links in Readme

on: push

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare Links in Readme
      run: |
        python .github/prep_readme_links.py -v